// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_wrapper_ap_ufixed_ap_fixed_16_6_5_3_0_config16_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] data_0_V_read;
input  [11:0] data_1_V_read;
input  [11:0] data_2_V_read;
input  [11:0] data_3_V_read;
input  [11:0] data_4_V_read;
input  [11:0] data_5_V_read;
input  [11:0] data_6_V_read;
input  [11:0] data_7_V_read;
input  [11:0] data_8_V_read;
input  [11:0] data_9_V_read;
input  [11:0] data_10_V_read;
input  [11:0] data_11_V_read;
input  [11:0] data_12_V_read;
input  [11:0] data_13_V_read;
input  [11:0] data_14_V_read;
input  [11:0] data_15_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[15:0] ap_return_0;
reg[15:0] ap_return_1;
reg[15:0] ap_return_2;
reg[15:0] ap_return_3;
reg[15:0] ap_return_4;
reg[15:0] ap_return_5;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln152_fu_884_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [5:0] outidx_address0;
reg    outidx_ce0;
wire   [1:0] outidx_q0;
wire   [5:0] w16_V_address0;
reg    w16_V_ce0;
wire   [18:0] w16_V_q0;
reg   [0:0] do_init_reg_238;
reg   [5:0] w_index30_reg_254;
reg   [11:0] data_0_V_read31_rewind_reg_268;
reg   [11:0] data_1_V_read32_rewind_reg_282;
reg   [11:0] data_2_V_read33_rewind_reg_296;
reg   [11:0] data_3_V_read34_rewind_reg_310;
reg   [11:0] data_4_V_read35_rewind_reg_324;
reg   [11:0] data_5_V_read36_rewind_reg_338;
reg   [11:0] data_6_V_read37_rewind_reg_352;
reg   [11:0] data_7_V_read38_rewind_reg_366;
reg   [11:0] data_8_V_read39_rewind_reg_380;
reg   [11:0] data_9_V_read40_rewind_reg_394;
reg   [11:0] data_10_V_read41_rewind_reg_408;
reg   [11:0] data_11_V_read42_rewind_reg_422;
reg   [11:0] data_12_V_read43_rewind_reg_436;
reg   [11:0] data_13_V_read44_rewind_reg_450;
reg   [11:0] data_14_V_read45_rewind_reg_464;
reg   [11:0] data_15_V_read46_rewind_reg_478;
reg   [31:0] in_index_0_i_i29_reg_492;
reg   [11:0] data_0_V_read31_phi_reg_506;
reg   [11:0] data_1_V_read32_phi_reg_518;
reg   [11:0] data_2_V_read33_phi_reg_530;
reg   [11:0] data_3_V_read34_phi_reg_542;
reg   [11:0] data_4_V_read35_phi_reg_554;
reg   [11:0] data_5_V_read36_phi_reg_566;
reg   [11:0] data_6_V_read37_phi_reg_578;
reg   [11:0] data_7_V_read38_phi_reg_590;
reg   [11:0] data_8_V_read39_phi_reg_602;
reg   [11:0] data_9_V_read40_phi_reg_614;
reg   [11:0] data_10_V_read41_phi_reg_626;
reg   [11:0] data_11_V_read42_phi_reg_638;
reg   [11:0] data_12_V_read43_phi_reg_650;
reg   [11:0] data_13_V_read44_phi_reg_662;
reg   [11:0] data_14_V_read45_phi_reg_674;
reg   [11:0] data_15_V_read46_phi_reg_686;
reg   [15:0] res_5_V_write_assign28_reg_698;
reg   [15:0] res_4_V_write_assign26_reg_712;
reg   [15:0] res_3_V_write_assign24_reg_726;
reg   [15:0] res_2_V_write_assign22_reg_740;
reg   [15:0] res_1_V_write_assign20_reg_754;
reg   [15:0] res_0_V_write_assign18_reg_768;
reg   [0:0] ap_phi_mux_do_init_phi_fu_242_p6;
wire   [5:0] w_index_fu_878_p2;
reg   [5:0] w_index_reg_1212;
reg   [0:0] icmp_ln152_reg_1217;
reg   [0:0] icmp_ln152_reg_1217_pp0_iter1_reg;
reg   [1:0] out_index_reg_1221;
reg   [15:0] trunc_ln2_reg_1227;
reg   [14:0] trunc_ln708_s_reg_1232;
wire   [31:0] select_ln170_fu_1002_p3;
reg   [31:0] select_ln170_reg_1237;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
wire    ap_block_pp0_stage0;
reg   [5:0] ap_phi_mux_w_index30_phi_fu_258_p6;
reg   [11:0] ap_phi_mux_data_0_V_read31_rewind_phi_fu_272_p6;
reg   [11:0] ap_phi_mux_data_1_V_read32_rewind_phi_fu_286_p6;
reg   [11:0] ap_phi_mux_data_2_V_read33_rewind_phi_fu_300_p6;
reg   [11:0] ap_phi_mux_data_3_V_read34_rewind_phi_fu_314_p6;
reg   [11:0] ap_phi_mux_data_4_V_read35_rewind_phi_fu_328_p6;
reg   [11:0] ap_phi_mux_data_5_V_read36_rewind_phi_fu_342_p6;
reg   [11:0] ap_phi_mux_data_6_V_read37_rewind_phi_fu_356_p6;
reg   [11:0] ap_phi_mux_data_7_V_read38_rewind_phi_fu_370_p6;
reg   [11:0] ap_phi_mux_data_8_V_read39_rewind_phi_fu_384_p6;
reg   [11:0] ap_phi_mux_data_9_V_read40_rewind_phi_fu_398_p6;
reg   [11:0] ap_phi_mux_data_10_V_read41_rewind_phi_fu_412_p6;
reg   [11:0] ap_phi_mux_data_11_V_read42_rewind_phi_fu_426_p6;
reg   [11:0] ap_phi_mux_data_12_V_read43_rewind_phi_fu_440_p6;
reg   [11:0] ap_phi_mux_data_13_V_read44_rewind_phi_fu_454_p6;
reg   [11:0] ap_phi_mux_data_14_V_read45_rewind_phi_fu_468_p6;
reg   [11:0] ap_phi_mux_data_15_V_read46_rewind_phi_fu_482_p6;
reg   [31:0] ap_phi_mux_in_index_0_i_i29_phi_fu_496_p6;
reg   [11:0] ap_phi_mux_data_0_V_read31_phi_phi_fu_510_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_0_V_read31_phi_reg_506;
reg   [11:0] ap_phi_reg_pp0_iter1_data_0_V_read31_phi_reg_506;
reg   [11:0] ap_phi_mux_data_1_V_read32_phi_phi_fu_522_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_1_V_read32_phi_reg_518;
reg   [11:0] ap_phi_reg_pp0_iter1_data_1_V_read32_phi_reg_518;
reg   [11:0] ap_phi_mux_data_2_V_read33_phi_phi_fu_534_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_2_V_read33_phi_reg_530;
reg   [11:0] ap_phi_reg_pp0_iter1_data_2_V_read33_phi_reg_530;
reg   [11:0] ap_phi_mux_data_3_V_read34_phi_phi_fu_546_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_3_V_read34_phi_reg_542;
reg   [11:0] ap_phi_reg_pp0_iter1_data_3_V_read34_phi_reg_542;
reg   [11:0] ap_phi_mux_data_4_V_read35_phi_phi_fu_558_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_4_V_read35_phi_reg_554;
reg   [11:0] ap_phi_reg_pp0_iter1_data_4_V_read35_phi_reg_554;
reg   [11:0] ap_phi_mux_data_5_V_read36_phi_phi_fu_570_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_5_V_read36_phi_reg_566;
reg   [11:0] ap_phi_reg_pp0_iter1_data_5_V_read36_phi_reg_566;
reg   [11:0] ap_phi_mux_data_6_V_read37_phi_phi_fu_582_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_6_V_read37_phi_reg_578;
reg   [11:0] ap_phi_reg_pp0_iter1_data_6_V_read37_phi_reg_578;
reg   [11:0] ap_phi_mux_data_7_V_read38_phi_phi_fu_594_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_7_V_read38_phi_reg_590;
reg   [11:0] ap_phi_reg_pp0_iter1_data_7_V_read38_phi_reg_590;
reg   [11:0] ap_phi_mux_data_8_V_read39_phi_phi_fu_606_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_8_V_read39_phi_reg_602;
reg   [11:0] ap_phi_reg_pp0_iter1_data_8_V_read39_phi_reg_602;
reg   [11:0] ap_phi_mux_data_9_V_read40_phi_phi_fu_618_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_9_V_read40_phi_reg_614;
reg   [11:0] ap_phi_reg_pp0_iter1_data_9_V_read40_phi_reg_614;
reg   [11:0] ap_phi_mux_data_10_V_read41_phi_phi_fu_630_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_10_V_read41_phi_reg_626;
reg   [11:0] ap_phi_reg_pp0_iter1_data_10_V_read41_phi_reg_626;
reg   [11:0] ap_phi_mux_data_11_V_read42_phi_phi_fu_642_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_11_V_read42_phi_reg_638;
reg   [11:0] ap_phi_reg_pp0_iter1_data_11_V_read42_phi_reg_638;
reg   [11:0] ap_phi_mux_data_12_V_read43_phi_phi_fu_654_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_12_V_read43_phi_reg_650;
reg   [11:0] ap_phi_reg_pp0_iter1_data_12_V_read43_phi_reg_650;
reg   [11:0] ap_phi_mux_data_13_V_read44_phi_phi_fu_666_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_13_V_read44_phi_reg_662;
reg   [11:0] ap_phi_reg_pp0_iter1_data_13_V_read44_phi_reg_662;
reg   [11:0] ap_phi_mux_data_14_V_read45_phi_phi_fu_678_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_14_V_read45_phi_reg_674;
reg   [11:0] ap_phi_reg_pp0_iter1_data_14_V_read45_phi_reg_674;
reg   [11:0] ap_phi_mux_data_15_V_read46_phi_phi_fu_690_p4;
wire   [11:0] ap_phi_reg_pp0_iter0_data_15_V_read46_phi_reg_686;
reg   [11:0] ap_phi_reg_pp0_iter1_data_15_V_read46_phi_reg_686;
reg   [15:0] ap_phi_mux_acc_V_5_1_phi_fu_861_p6;
reg   [15:0] ap_phi_mux_acc_V_4_1_phi_fu_846_p6;
reg   [15:0] ap_phi_mux_acc_V_3_1_phi_fu_831_p6;
reg   [15:0] ap_phi_mux_acc_V_2_1_phi_fu_816_p6;
reg   [15:0] ap_phi_mux_acc_V_1_1_phi_fu_801_p6;
reg   [15:0] ap_phi_mux_acc_V_0_1_phi_fu_786_p6;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_V_0_1_reg_782;
wire   [15:0] acc_0_V_fu_1026_p2;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_V_1_1_reg_797;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_V_2_1_reg_812;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_V_3_1_reg_827;
wire   [15:0] acc_3_V_fu_1059_p2;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_V_4_1_reg_842;
wire   [15:0] ap_phi_reg_pp0_iter2_acc_V_5_1_reg_857;
wire   [63:0] zext_ln156_fu_872_p1;
wire   [3:0] tmp_s_fu_894_p17;
wire   [11:0] tmp_s_fu_894_p18;
wire  signed [11:0] trunc_ln162_1_fu_932_p1;
wire  signed [19:0] mul_ln1118_fu_1108_p2;
wire  signed [6:0] tmp_32_fu_957_p4;
wire  signed [18:0] mul_ln1118_34_fu_1115_p2;
wire   [31:0] in_index_fu_980_p2;
wire   [27:0] tmp_2_fu_986_p4;
wire   [0:0] icmp_ln170_fu_996_p2;
wire   [15:0] phi_ln_fu_1013_p6;
wire   [2:0] phi_ln1265_1_fu_1037_p9;
wire   [15:0] phi_ln1265_1_fu_1037_p10;
wire  signed [15:0] sext_ln708_fu_1034_p1;
wire   [11:0] mul_ln1118_fu_1108_p1;
wire   [11:0] mul_ln1118_34_fu_1115_p0;
reg   [15:0] ap_return_0_preg;
reg   [15:0] ap_return_1_preg;
reg   [15:0] ap_return_2_preg;
reg   [15:0] ap_return_3_preg;
reg   [15:0] ap_return_4_preg;
reg   [15:0] ap_return_5_preg;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [18:0] mul_ln1118_34_fu_1115_p00;
wire   [19:0] mul_ln1118_fu_1108_p10;
reg    ap_condition_243;
reg    ap_condition_40;
reg    ap_condition_229;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_return_0_preg = 16'd0;
#0 ap_return_1_preg = 16'd0;
#0 ap_return_2_preg = 16'd0;
#0 ap_return_3_preg = 16'd0;
#0 ap_return_4_preg = 16'd0;
#0 ap_return_5_preg = 16'd0;
end

dense_wrapper_ap_ufixed_ap_fixed_16_6_5_3_0_config16_s_oug8j #(
    .DataWidth( 2 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
outidx_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(outidx_address0),
    .ce0(outidx_ce0),
    .q0(outidx_q0)
);

dense_wrapper_ap_ufixed_ap_fixed_16_6_5_3_0_config16_s_w1hbi #(
    .DataWidth( 19 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
w16_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w16_V_address0),
    .ce0(w16_V_ce0),
    .q0(w16_V_q0)
);

myproject_axi_mux_164_12_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .din2_WIDTH( 12 ),
    .din3_WIDTH( 12 ),
    .din4_WIDTH( 12 ),
    .din5_WIDTH( 12 ),
    .din6_WIDTH( 12 ),
    .din7_WIDTH( 12 ),
    .din8_WIDTH( 12 ),
    .din9_WIDTH( 12 ),
    .din10_WIDTH( 12 ),
    .din11_WIDTH( 12 ),
    .din12_WIDTH( 12 ),
    .din13_WIDTH( 12 ),
    .din14_WIDTH( 12 ),
    .din15_WIDTH( 12 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 12 ))
myproject_axi_mux_164_12_1_1_U2691(
    .din0(ap_phi_mux_data_0_V_read31_phi_phi_fu_510_p4),
    .din1(ap_phi_mux_data_1_V_read32_phi_phi_fu_522_p4),
    .din2(ap_phi_mux_data_2_V_read33_phi_phi_fu_534_p4),
    .din3(ap_phi_mux_data_3_V_read34_phi_phi_fu_546_p4),
    .din4(ap_phi_mux_data_4_V_read35_phi_phi_fu_558_p4),
    .din5(ap_phi_mux_data_5_V_read36_phi_phi_fu_570_p4),
    .din6(ap_phi_mux_data_6_V_read37_phi_phi_fu_582_p4),
    .din7(ap_phi_mux_data_7_V_read38_phi_phi_fu_594_p4),
    .din8(ap_phi_mux_data_8_V_read39_phi_phi_fu_606_p4),
    .din9(ap_phi_mux_data_9_V_read40_phi_phi_fu_618_p4),
    .din10(ap_phi_mux_data_10_V_read41_phi_phi_fu_630_p4),
    .din11(ap_phi_mux_data_11_V_read42_phi_phi_fu_642_p4),
    .din12(ap_phi_mux_data_12_V_read43_phi_phi_fu_654_p4),
    .din13(ap_phi_mux_data_13_V_read44_phi_phi_fu_666_p4),
    .din14(ap_phi_mux_data_14_V_read45_phi_phi_fu_678_p4),
    .din15(ap_phi_mux_data_15_V_read46_phi_phi_fu_690_p4),
    .din16(tmp_s_fu_894_p17),
    .dout(tmp_s_fu_894_p18)
);

myproject_axi_mux_42_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 16 ))
myproject_axi_mux_42_16_1_1_U2692(
    .din0(res_0_V_write_assign18_reg_768),
    .din1(res_1_V_write_assign20_reg_754),
    .din2(res_2_V_write_assign22_reg_740),
    .din3(res_2_V_write_assign22_reg_740),
    .din4(out_index_reg_1221),
    .dout(phi_ln_fu_1013_p6)
);

myproject_axi_mux_83_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .din3_WIDTH( 16 ),
    .din4_WIDTH( 16 ),
    .din5_WIDTH( 16 ),
    .din6_WIDTH( 16 ),
    .din7_WIDTH( 16 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
myproject_axi_mux_83_16_1_1_U2693(
    .din0(res_3_V_write_assign24_reg_726),
    .din1(res_4_V_write_assign26_reg_712),
    .din2(res_5_V_write_assign28_reg_698),
    .din3(res_5_V_write_assign28_reg_698),
    .din4(res_5_V_write_assign28_reg_698),
    .din5(res_5_V_write_assign28_reg_698),
    .din6(res_5_V_write_assign28_reg_698),
    .din7(res_5_V_write_assign28_reg_698),
    .din8(phi_ln1265_1_fu_1037_p9),
    .dout(phi_ln1265_1_fu_1037_p10)
);

myproject_axi_mul_mul_12s_12ns_20_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 20 ))
myproject_axi_mul_mul_12s_12ns_20_1_1_U2694(
    .din0(trunc_ln162_1_fu_932_p1),
    .din1(mul_ln1118_fu_1108_p1),
    .dout(mul_ln1118_fu_1108_p2)
);

myproject_axi_mul_mul_12ns_7s_19_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 19 ))
myproject_axi_mul_mul_12ns_7s_19_1_1_U2695(
    .din0(mul_ln1118_34_fu_1115_p0),
    .din1(tmp_32_fu_957_p4),
    .dout(mul_ln1118_34_fu_1115_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_0_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_0_preg <= ap_phi_mux_acc_V_0_1_phi_fu_786_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_1_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_1_preg <= ap_phi_mux_acc_V_1_1_phi_fu_801_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_2_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_2_preg <= ap_phi_mux_acc_V_2_1_phi_fu_816_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_3_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_3_preg <= ap_phi_mux_acc_V_3_1_phi_fu_831_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_4_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_4_preg <= ap_phi_mux_acc_V_4_1_phi_fu_846_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_5_preg <= 16'd0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            ap_return_5_preg <= ap_phi_mux_acc_V_5_1_phi_fu_861_p6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_0_V_read31_phi_reg_506 <= data_0_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_0_V_read31_phi_reg_506 <= ap_phi_reg_pp0_iter0_data_0_V_read31_phi_reg_506;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_10_V_read41_phi_reg_626 <= data_10_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_10_V_read41_phi_reg_626 <= ap_phi_reg_pp0_iter0_data_10_V_read41_phi_reg_626;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_11_V_read42_phi_reg_638 <= data_11_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_11_V_read42_phi_reg_638 <= ap_phi_reg_pp0_iter0_data_11_V_read42_phi_reg_638;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_12_V_read43_phi_reg_650 <= data_12_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_12_V_read43_phi_reg_650 <= ap_phi_reg_pp0_iter0_data_12_V_read43_phi_reg_650;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_13_V_read44_phi_reg_662 <= data_13_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_13_V_read44_phi_reg_662 <= ap_phi_reg_pp0_iter0_data_13_V_read44_phi_reg_662;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_14_V_read45_phi_reg_674 <= data_14_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_14_V_read45_phi_reg_674 <= ap_phi_reg_pp0_iter0_data_14_V_read45_phi_reg_674;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_15_V_read46_phi_reg_686 <= data_15_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_15_V_read46_phi_reg_686 <= ap_phi_reg_pp0_iter0_data_15_V_read46_phi_reg_686;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_1_V_read32_phi_reg_518 <= data_1_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_1_V_read32_phi_reg_518 <= ap_phi_reg_pp0_iter0_data_1_V_read32_phi_reg_518;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_2_V_read33_phi_reg_530 <= data_2_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_2_V_read33_phi_reg_530 <= ap_phi_reg_pp0_iter0_data_2_V_read33_phi_reg_530;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_3_V_read34_phi_reg_542 <= data_3_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_3_V_read34_phi_reg_542 <= ap_phi_reg_pp0_iter0_data_3_V_read34_phi_reg_542;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_4_V_read35_phi_reg_554 <= data_4_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_4_V_read35_phi_reg_554 <= ap_phi_reg_pp0_iter0_data_4_V_read35_phi_reg_554;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_5_V_read36_phi_reg_566 <= data_5_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_5_V_read36_phi_reg_566 <= ap_phi_reg_pp0_iter0_data_5_V_read36_phi_reg_566;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_6_V_read37_phi_reg_578 <= data_6_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_6_V_read37_phi_reg_578 <= ap_phi_reg_pp0_iter0_data_6_V_read37_phi_reg_578;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_7_V_read38_phi_reg_590 <= data_7_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_7_V_read38_phi_reg_590 <= ap_phi_reg_pp0_iter0_data_7_V_read38_phi_reg_590;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_8_V_read39_phi_reg_602 <= data_8_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_8_V_read39_phi_reg_602 <= ap_phi_reg_pp0_iter0_data_8_V_read39_phi_reg_602;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_40)) begin
        if ((ap_phi_mux_do_init_phi_fu_242_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_data_9_V_read40_phi_reg_614 <= data_9_V_read;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_data_9_V_read40_phi_reg_614 <= ap_phi_reg_pp0_iter0_data_9_V_read40_phi_reg_614;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_0_V_read31_phi_reg_506 <= ap_phi_mux_data_0_V_read31_rewind_phi_fu_272_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_0_V_read31_phi_reg_506 <= ap_phi_reg_pp0_iter1_data_0_V_read31_phi_reg_506;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_10_V_read41_phi_reg_626 <= ap_phi_mux_data_10_V_read41_rewind_phi_fu_412_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_10_V_read41_phi_reg_626 <= ap_phi_reg_pp0_iter1_data_10_V_read41_phi_reg_626;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_11_V_read42_phi_reg_638 <= ap_phi_mux_data_11_V_read42_rewind_phi_fu_426_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_11_V_read42_phi_reg_638 <= ap_phi_reg_pp0_iter1_data_11_V_read42_phi_reg_638;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_12_V_read43_phi_reg_650 <= ap_phi_mux_data_12_V_read43_rewind_phi_fu_440_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_12_V_read43_phi_reg_650 <= ap_phi_reg_pp0_iter1_data_12_V_read43_phi_reg_650;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_13_V_read44_phi_reg_662 <= ap_phi_mux_data_13_V_read44_rewind_phi_fu_454_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_13_V_read44_phi_reg_662 <= ap_phi_reg_pp0_iter1_data_13_V_read44_phi_reg_662;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_14_V_read45_phi_reg_674 <= ap_phi_mux_data_14_V_read45_rewind_phi_fu_468_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_14_V_read45_phi_reg_674 <= ap_phi_reg_pp0_iter1_data_14_V_read45_phi_reg_674;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_15_V_read46_phi_reg_686 <= ap_phi_mux_data_15_V_read46_rewind_phi_fu_482_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_15_V_read46_phi_reg_686 <= ap_phi_reg_pp0_iter1_data_15_V_read46_phi_reg_686;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_1_V_read32_phi_reg_518 <= ap_phi_mux_data_1_V_read32_rewind_phi_fu_286_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_1_V_read32_phi_reg_518 <= ap_phi_reg_pp0_iter1_data_1_V_read32_phi_reg_518;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_2_V_read33_phi_reg_530 <= ap_phi_mux_data_2_V_read33_rewind_phi_fu_300_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_2_V_read33_phi_reg_530 <= ap_phi_reg_pp0_iter1_data_2_V_read33_phi_reg_530;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_3_V_read34_phi_reg_542 <= ap_phi_mux_data_3_V_read34_rewind_phi_fu_314_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_3_V_read34_phi_reg_542 <= ap_phi_reg_pp0_iter1_data_3_V_read34_phi_reg_542;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_4_V_read35_phi_reg_554 <= ap_phi_mux_data_4_V_read35_rewind_phi_fu_328_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_4_V_read35_phi_reg_554 <= ap_phi_reg_pp0_iter1_data_4_V_read35_phi_reg_554;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_5_V_read36_phi_reg_566 <= ap_phi_mux_data_5_V_read36_rewind_phi_fu_342_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_5_V_read36_phi_reg_566 <= ap_phi_reg_pp0_iter1_data_5_V_read36_phi_reg_566;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_6_V_read37_phi_reg_578 <= ap_phi_mux_data_6_V_read37_rewind_phi_fu_356_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_6_V_read37_phi_reg_578 <= ap_phi_reg_pp0_iter1_data_6_V_read37_phi_reg_578;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_7_V_read38_phi_reg_590 <= ap_phi_mux_data_7_V_read38_rewind_phi_fu_370_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_7_V_read38_phi_reg_590 <= ap_phi_reg_pp0_iter1_data_7_V_read38_phi_reg_590;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_8_V_read39_phi_reg_602 <= ap_phi_mux_data_8_V_read39_rewind_phi_fu_384_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_8_V_read39_phi_reg_602 <= ap_phi_reg_pp0_iter1_data_8_V_read39_phi_reg_602;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_229)) begin
        if ((do_init_reg_238 == 1'd0)) begin
            data_9_V_read40_phi_reg_614 <= ap_phi_mux_data_9_V_read40_rewind_phi_fu_398_p6;
        end else if ((1'b1 == 1'b1)) begin
            data_9_V_read40_phi_reg_614 <= ap_phi_reg_pp0_iter1_data_9_V_read40_phi_reg_614;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        do_init_reg_238 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_238 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        in_index_0_i_i29_reg_492 <= select_ln170_reg_1237;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        in_index_0_i_i29_reg_492 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_0_V_write_assign18_reg_768 <= ap_phi_mux_acc_V_0_1_phi_fu_786_p6;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_0_V_write_assign18_reg_768 <= 16'd65472;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_1_V_write_assign20_reg_754 <= ap_phi_mux_acc_V_1_1_phi_fu_801_p6;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_1_V_write_assign20_reg_754 <= 16'd352;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_2_V_write_assign22_reg_740 <= ap_phi_mux_acc_V_2_1_phi_fu_816_p6;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_2_V_write_assign22_reg_740 <= 16'd288;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_3_V_write_assign24_reg_726 <= ap_phi_mux_acc_V_3_1_phi_fu_831_p6;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_3_V_write_assign24_reg_726 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_4_V_write_assign26_reg_712 <= ap_phi_mux_acc_V_4_1_phi_fu_846_p6;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_4_V_write_assign26_reg_712 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        res_5_V_write_assign28_reg_698 <= ap_phi_mux_acc_V_5_1_phi_fu_861_p6;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        res_5_V_write_assign28_reg_698 <= 16'd64704;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        w_index30_reg_254 <= w_index_reg_1212;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        w_index30_reg_254 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        data_0_V_read31_rewind_reg_268 <= data_0_V_read31_phi_reg_506;
        data_10_V_read41_rewind_reg_408 <= data_10_V_read41_phi_reg_626;
        data_11_V_read42_rewind_reg_422 <= data_11_V_read42_phi_reg_638;
        data_12_V_read43_rewind_reg_436 <= data_12_V_read43_phi_reg_650;
        data_13_V_read44_rewind_reg_450 <= data_13_V_read44_phi_reg_662;
        data_14_V_read45_rewind_reg_464 <= data_14_V_read45_phi_reg_674;
        data_15_V_read46_rewind_reg_478 <= data_15_V_read46_phi_reg_686;
        data_1_V_read32_rewind_reg_282 <= data_1_V_read32_phi_reg_518;
        data_2_V_read33_rewind_reg_296 <= data_2_V_read33_phi_reg_530;
        data_3_V_read34_rewind_reg_310 <= data_3_V_read34_phi_reg_542;
        data_4_V_read35_rewind_reg_324 <= data_4_V_read35_phi_reg_554;
        data_5_V_read36_rewind_reg_338 <= data_5_V_read36_phi_reg_566;
        data_6_V_read37_rewind_reg_352 <= data_6_V_read37_phi_reg_578;
        data_7_V_read38_rewind_reg_366 <= data_7_V_read38_phi_reg_590;
        data_8_V_read39_rewind_reg_380 <= data_8_V_read39_phi_reg_602;
        data_9_V_read40_rewind_reg_394 <= data_9_V_read40_phi_reg_614;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln152_reg_1217 <= icmp_ln152_fu_884_p2;
        icmp_ln152_reg_1217_pp0_iter1_reg <= icmp_ln152_reg_1217;
        out_index_reg_1221 <= outidx_q0;
        trunc_ln2_reg_1227 <= {{mul_ln1118_fu_1108_p2[19:4]}};
        trunc_ln708_s_reg_1232 <= {{mul_ln1118_34_fu_1115_p2[18:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        select_ln170_reg_1237 <= select_ln170_fu_1002_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w_index_reg_1212 <= w_index_fu_878_p2;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if ((out_index_reg_1221 == 2'd0)) begin
        ap_phi_mux_acc_V_0_1_phi_fu_786_p6 = acc_0_V_fu_1026_p2;
    end else if (((out_index_reg_1221 == 2'd1) | (~(out_index_reg_1221 == 2'd1) & ~(out_index_reg_1221 == 2'd0)))) begin
        ap_phi_mux_acc_V_0_1_phi_fu_786_p6 = res_0_V_write_assign18_reg_768;
    end else begin
        ap_phi_mux_acc_V_0_1_phi_fu_786_p6 = ap_phi_reg_pp0_iter2_acc_V_0_1_reg_782;
    end
end

always @ (*) begin
    if ((out_index_reg_1221 == 2'd1)) begin
        ap_phi_mux_acc_V_1_1_phi_fu_801_p6 = acc_0_V_fu_1026_p2;
    end else if (((out_index_reg_1221 == 2'd0) | (~(out_index_reg_1221 == 2'd1) & ~(out_index_reg_1221 == 2'd0)))) begin
        ap_phi_mux_acc_V_1_1_phi_fu_801_p6 = res_1_V_write_assign20_reg_754;
    end else begin
        ap_phi_mux_acc_V_1_1_phi_fu_801_p6 = ap_phi_reg_pp0_iter2_acc_V_1_1_reg_797;
    end
end

always @ (*) begin
    if (((out_index_reg_1221 == 2'd1) | (out_index_reg_1221 == 2'd0))) begin
        ap_phi_mux_acc_V_2_1_phi_fu_816_p6 = res_2_V_write_assign22_reg_740;
    end else if ((~(out_index_reg_1221 == 2'd1) & ~(out_index_reg_1221 == 2'd0))) begin
        ap_phi_mux_acc_V_2_1_phi_fu_816_p6 = acc_0_V_fu_1026_p2;
    end else begin
        ap_phi_mux_acc_V_2_1_phi_fu_816_p6 = ap_phi_reg_pp0_iter2_acc_V_2_1_reg_812;
    end
end

always @ (*) begin
    if ((out_index_reg_1221 == 2'd0)) begin
        ap_phi_mux_acc_V_3_1_phi_fu_831_p6 = acc_3_V_fu_1059_p2;
    end else if (((out_index_reg_1221 == 2'd1) | (~(out_index_reg_1221 == 2'd1) & ~(out_index_reg_1221 == 2'd0)))) begin
        ap_phi_mux_acc_V_3_1_phi_fu_831_p6 = res_3_V_write_assign24_reg_726;
    end else begin
        ap_phi_mux_acc_V_3_1_phi_fu_831_p6 = ap_phi_reg_pp0_iter2_acc_V_3_1_reg_827;
    end
end

always @ (*) begin
    if ((out_index_reg_1221 == 2'd1)) begin
        ap_phi_mux_acc_V_4_1_phi_fu_846_p6 = acc_3_V_fu_1059_p2;
    end else if (((out_index_reg_1221 == 2'd0) | (~(out_index_reg_1221 == 2'd1) & ~(out_index_reg_1221 == 2'd0)))) begin
        ap_phi_mux_acc_V_4_1_phi_fu_846_p6 = res_4_V_write_assign26_reg_712;
    end else begin
        ap_phi_mux_acc_V_4_1_phi_fu_846_p6 = ap_phi_reg_pp0_iter2_acc_V_4_1_reg_842;
    end
end

always @ (*) begin
    if (((out_index_reg_1221 == 2'd1) | (out_index_reg_1221 == 2'd0))) begin
        ap_phi_mux_acc_V_5_1_phi_fu_861_p6 = res_5_V_write_assign28_reg_698;
    end else if ((~(out_index_reg_1221 == 2'd1) & ~(out_index_reg_1221 == 2'd0))) begin
        ap_phi_mux_acc_V_5_1_phi_fu_861_p6 = acc_3_V_fu_1059_p2;
    end else begin
        ap_phi_mux_acc_V_5_1_phi_fu_861_p6 = ap_phi_reg_pp0_iter2_acc_V_5_1_reg_857;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_0_V_read31_phi_phi_fu_510_p4 = ap_phi_mux_data_0_V_read31_rewind_phi_fu_272_p6;
    end else begin
        ap_phi_mux_data_0_V_read31_phi_phi_fu_510_p4 = ap_phi_reg_pp0_iter1_data_0_V_read31_phi_reg_506;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_0_V_read31_rewind_phi_fu_272_p6 = data_0_V_read31_phi_reg_506;
    end else begin
        ap_phi_mux_data_0_V_read31_rewind_phi_fu_272_p6 = data_0_V_read31_rewind_reg_268;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_10_V_read41_phi_phi_fu_630_p4 = ap_phi_mux_data_10_V_read41_rewind_phi_fu_412_p6;
    end else begin
        ap_phi_mux_data_10_V_read41_phi_phi_fu_630_p4 = ap_phi_reg_pp0_iter1_data_10_V_read41_phi_reg_626;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_10_V_read41_rewind_phi_fu_412_p6 = data_10_V_read41_phi_reg_626;
    end else begin
        ap_phi_mux_data_10_V_read41_rewind_phi_fu_412_p6 = data_10_V_read41_rewind_reg_408;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_11_V_read42_phi_phi_fu_642_p4 = ap_phi_mux_data_11_V_read42_rewind_phi_fu_426_p6;
    end else begin
        ap_phi_mux_data_11_V_read42_phi_phi_fu_642_p4 = ap_phi_reg_pp0_iter1_data_11_V_read42_phi_reg_638;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_11_V_read42_rewind_phi_fu_426_p6 = data_11_V_read42_phi_reg_638;
    end else begin
        ap_phi_mux_data_11_V_read42_rewind_phi_fu_426_p6 = data_11_V_read42_rewind_reg_422;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_12_V_read43_phi_phi_fu_654_p4 = ap_phi_mux_data_12_V_read43_rewind_phi_fu_440_p6;
    end else begin
        ap_phi_mux_data_12_V_read43_phi_phi_fu_654_p4 = ap_phi_reg_pp0_iter1_data_12_V_read43_phi_reg_650;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_12_V_read43_rewind_phi_fu_440_p6 = data_12_V_read43_phi_reg_650;
    end else begin
        ap_phi_mux_data_12_V_read43_rewind_phi_fu_440_p6 = data_12_V_read43_rewind_reg_436;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_13_V_read44_phi_phi_fu_666_p4 = ap_phi_mux_data_13_V_read44_rewind_phi_fu_454_p6;
    end else begin
        ap_phi_mux_data_13_V_read44_phi_phi_fu_666_p4 = ap_phi_reg_pp0_iter1_data_13_V_read44_phi_reg_662;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_13_V_read44_rewind_phi_fu_454_p6 = data_13_V_read44_phi_reg_662;
    end else begin
        ap_phi_mux_data_13_V_read44_rewind_phi_fu_454_p6 = data_13_V_read44_rewind_reg_450;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_14_V_read45_phi_phi_fu_678_p4 = ap_phi_mux_data_14_V_read45_rewind_phi_fu_468_p6;
    end else begin
        ap_phi_mux_data_14_V_read45_phi_phi_fu_678_p4 = ap_phi_reg_pp0_iter1_data_14_V_read45_phi_reg_674;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_14_V_read45_rewind_phi_fu_468_p6 = data_14_V_read45_phi_reg_674;
    end else begin
        ap_phi_mux_data_14_V_read45_rewind_phi_fu_468_p6 = data_14_V_read45_rewind_reg_464;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_15_V_read46_phi_phi_fu_690_p4 = ap_phi_mux_data_15_V_read46_rewind_phi_fu_482_p6;
    end else begin
        ap_phi_mux_data_15_V_read46_phi_phi_fu_690_p4 = ap_phi_reg_pp0_iter1_data_15_V_read46_phi_reg_686;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_15_V_read46_rewind_phi_fu_482_p6 = data_15_V_read46_phi_reg_686;
    end else begin
        ap_phi_mux_data_15_V_read46_rewind_phi_fu_482_p6 = data_15_V_read46_rewind_reg_478;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_1_V_read32_phi_phi_fu_522_p4 = ap_phi_mux_data_1_V_read32_rewind_phi_fu_286_p6;
    end else begin
        ap_phi_mux_data_1_V_read32_phi_phi_fu_522_p4 = ap_phi_reg_pp0_iter1_data_1_V_read32_phi_reg_518;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_1_V_read32_rewind_phi_fu_286_p6 = data_1_V_read32_phi_reg_518;
    end else begin
        ap_phi_mux_data_1_V_read32_rewind_phi_fu_286_p6 = data_1_V_read32_rewind_reg_282;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_2_V_read33_phi_phi_fu_534_p4 = ap_phi_mux_data_2_V_read33_rewind_phi_fu_300_p6;
    end else begin
        ap_phi_mux_data_2_V_read33_phi_phi_fu_534_p4 = ap_phi_reg_pp0_iter1_data_2_V_read33_phi_reg_530;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_2_V_read33_rewind_phi_fu_300_p6 = data_2_V_read33_phi_reg_530;
    end else begin
        ap_phi_mux_data_2_V_read33_rewind_phi_fu_300_p6 = data_2_V_read33_rewind_reg_296;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_3_V_read34_phi_phi_fu_546_p4 = ap_phi_mux_data_3_V_read34_rewind_phi_fu_314_p6;
    end else begin
        ap_phi_mux_data_3_V_read34_phi_phi_fu_546_p4 = ap_phi_reg_pp0_iter1_data_3_V_read34_phi_reg_542;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_3_V_read34_rewind_phi_fu_314_p6 = data_3_V_read34_phi_reg_542;
    end else begin
        ap_phi_mux_data_3_V_read34_rewind_phi_fu_314_p6 = data_3_V_read34_rewind_reg_310;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_4_V_read35_phi_phi_fu_558_p4 = ap_phi_mux_data_4_V_read35_rewind_phi_fu_328_p6;
    end else begin
        ap_phi_mux_data_4_V_read35_phi_phi_fu_558_p4 = ap_phi_reg_pp0_iter1_data_4_V_read35_phi_reg_554;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_4_V_read35_rewind_phi_fu_328_p6 = data_4_V_read35_phi_reg_554;
    end else begin
        ap_phi_mux_data_4_V_read35_rewind_phi_fu_328_p6 = data_4_V_read35_rewind_reg_324;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_5_V_read36_phi_phi_fu_570_p4 = ap_phi_mux_data_5_V_read36_rewind_phi_fu_342_p6;
    end else begin
        ap_phi_mux_data_5_V_read36_phi_phi_fu_570_p4 = ap_phi_reg_pp0_iter1_data_5_V_read36_phi_reg_566;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_5_V_read36_rewind_phi_fu_342_p6 = data_5_V_read36_phi_reg_566;
    end else begin
        ap_phi_mux_data_5_V_read36_rewind_phi_fu_342_p6 = data_5_V_read36_rewind_reg_338;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_6_V_read37_phi_phi_fu_582_p4 = ap_phi_mux_data_6_V_read37_rewind_phi_fu_356_p6;
    end else begin
        ap_phi_mux_data_6_V_read37_phi_phi_fu_582_p4 = ap_phi_reg_pp0_iter1_data_6_V_read37_phi_reg_578;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_6_V_read37_rewind_phi_fu_356_p6 = data_6_V_read37_phi_reg_578;
    end else begin
        ap_phi_mux_data_6_V_read37_rewind_phi_fu_356_p6 = data_6_V_read37_rewind_reg_352;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_7_V_read38_phi_phi_fu_594_p4 = ap_phi_mux_data_7_V_read38_rewind_phi_fu_370_p6;
    end else begin
        ap_phi_mux_data_7_V_read38_phi_phi_fu_594_p4 = ap_phi_reg_pp0_iter1_data_7_V_read38_phi_reg_590;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_7_V_read38_rewind_phi_fu_370_p6 = data_7_V_read38_phi_reg_590;
    end else begin
        ap_phi_mux_data_7_V_read38_rewind_phi_fu_370_p6 = data_7_V_read38_rewind_reg_366;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_8_V_read39_phi_phi_fu_606_p4 = ap_phi_mux_data_8_V_read39_rewind_phi_fu_384_p6;
    end else begin
        ap_phi_mux_data_8_V_read39_phi_phi_fu_606_p4 = ap_phi_reg_pp0_iter1_data_8_V_read39_phi_reg_602;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_8_V_read39_rewind_phi_fu_384_p6 = data_8_V_read39_phi_reg_602;
    end else begin
        ap_phi_mux_data_8_V_read39_rewind_phi_fu_384_p6 = data_8_V_read39_rewind_reg_380;
    end
end

always @ (*) begin
    if ((do_init_reg_238 == 1'd0)) begin
        ap_phi_mux_data_9_V_read40_phi_phi_fu_618_p4 = ap_phi_mux_data_9_V_read40_rewind_phi_fu_398_p6;
    end else begin
        ap_phi_mux_data_9_V_read40_phi_phi_fu_618_p4 = ap_phi_reg_pp0_iter1_data_9_V_read40_phi_reg_614;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_data_9_V_read40_rewind_phi_fu_398_p6 = data_9_V_read40_phi_reg_614;
    end else begin
        ap_phi_mux_data_9_V_read40_rewind_phi_fu_398_p6 = data_9_V_read40_rewind_reg_394;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_243)) begin
        if ((icmp_ln152_reg_1217 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_242_p6 = 1'd1;
        end else if ((icmp_ln152_reg_1217 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_242_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_242_p6 = do_init_reg_238;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_242_p6 = do_init_reg_238;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_in_index_0_i_i29_phi_fu_496_p6 = 32'd0;
        end else if ((icmp_ln152_reg_1217_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_in_index_0_i_i29_phi_fu_496_p6 = select_ln170_reg_1237;
        end else begin
            ap_phi_mux_in_index_0_i_i29_phi_fu_496_p6 = in_index_0_i_i29_reg_492;
        end
    end else begin
        ap_phi_mux_in_index_0_i_i29_phi_fu_496_p6 = in_index_0_i_i29_reg_492;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_243)) begin
        if ((icmp_ln152_reg_1217 == 1'd1)) begin
            ap_phi_mux_w_index30_phi_fu_258_p6 = 6'd0;
        end else if ((icmp_ln152_reg_1217 == 1'd0)) begin
            ap_phi_mux_w_index30_phi_fu_258_p6 = w_index_reg_1212;
        end else begin
            ap_phi_mux_w_index30_phi_fu_258_p6 = w_index30_reg_254;
        end
    end else begin
        ap_phi_mux_w_index30_phi_fu_258_p6 = w_index30_reg_254;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_fu_884_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_0 = ap_phi_mux_acc_V_0_1_phi_fu_786_p6;
    end else begin
        ap_return_0 = ap_return_0_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_1 = ap_phi_mux_acc_V_1_1_phi_fu_801_p6;
    end else begin
        ap_return_1 = ap_return_1_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_2 = ap_phi_mux_acc_V_2_1_phi_fu_816_p6;
    end else begin
        ap_return_2 = ap_return_2_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_3 = ap_phi_mux_acc_V_3_1_phi_fu_831_p6;
    end else begin
        ap_return_3 = ap_return_3_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_4 = ap_phi_mux_acc_V_4_1_phi_fu_846_p6;
    end else begin
        ap_return_4 = ap_return_4_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln152_reg_1217_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_return_5 = ap_phi_mux_acc_V_5_1_phi_fu_861_p6;
    end else begin
        ap_return_5 = ap_return_5_preg;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        outidx_ce0 = 1'b1;
    end else begin
        outidx_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w16_V_ce0 = 1'b1;
    end else begin
        w16_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_0_V_fu_1026_p2 = (phi_ln_fu_1013_p6 + trunc_ln2_reg_1227);

assign acc_3_V_fu_1059_p2 = ($signed(phi_ln1265_1_fu_1037_p10) + $signed(sext_ln708_fu_1034_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_229 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_243 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_40 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_data_0_V_read31_phi_reg_506 = 'bx;

assign ap_phi_reg_pp0_iter0_data_10_V_read41_phi_reg_626 = 'bx;

assign ap_phi_reg_pp0_iter0_data_11_V_read42_phi_reg_638 = 'bx;

assign ap_phi_reg_pp0_iter0_data_12_V_read43_phi_reg_650 = 'bx;

assign ap_phi_reg_pp0_iter0_data_13_V_read44_phi_reg_662 = 'bx;

assign ap_phi_reg_pp0_iter0_data_14_V_read45_phi_reg_674 = 'bx;

assign ap_phi_reg_pp0_iter0_data_15_V_read46_phi_reg_686 = 'bx;

assign ap_phi_reg_pp0_iter0_data_1_V_read32_phi_reg_518 = 'bx;

assign ap_phi_reg_pp0_iter0_data_2_V_read33_phi_reg_530 = 'bx;

assign ap_phi_reg_pp0_iter0_data_3_V_read34_phi_reg_542 = 'bx;

assign ap_phi_reg_pp0_iter0_data_4_V_read35_phi_reg_554 = 'bx;

assign ap_phi_reg_pp0_iter0_data_5_V_read36_phi_reg_566 = 'bx;

assign ap_phi_reg_pp0_iter0_data_6_V_read37_phi_reg_578 = 'bx;

assign ap_phi_reg_pp0_iter0_data_7_V_read38_phi_reg_590 = 'bx;

assign ap_phi_reg_pp0_iter0_data_8_V_read39_phi_reg_602 = 'bx;

assign ap_phi_reg_pp0_iter0_data_9_V_read40_phi_reg_614 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_V_0_1_reg_782 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_V_1_1_reg_797 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_V_2_1_reg_812 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_V_3_1_reg_827 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_V_4_1_reg_842 = 'bx;

assign ap_phi_reg_pp0_iter2_acc_V_5_1_reg_857 = 'bx;

assign icmp_ln152_fu_884_p2 = ((ap_phi_mux_w_index30_phi_fu_258_p6 == 6'd47) ? 1'b1 : 1'b0);

assign icmp_ln170_fu_996_p2 = (($signed(tmp_2_fu_986_p4) > $signed(28'd0)) ? 1'b1 : 1'b0);

assign in_index_fu_980_p2 = (ap_phi_mux_in_index_0_i_i29_phi_fu_496_p6 + 32'd1);

assign mul_ln1118_34_fu_1115_p0 = mul_ln1118_34_fu_1115_p00;

assign mul_ln1118_34_fu_1115_p00 = tmp_s_fu_894_p18;

assign mul_ln1118_fu_1108_p1 = mul_ln1118_fu_1108_p10;

assign mul_ln1118_fu_1108_p10 = tmp_s_fu_894_p18;

assign outidx_address0 = zext_ln156_fu_872_p1;

assign phi_ln1265_1_fu_1037_p9 = out_index_reg_1221;

assign select_ln170_fu_1002_p3 = ((icmp_ln170_fu_996_p2[0:0] === 1'b1) ? 32'd0 : in_index_fu_980_p2);

assign sext_ln708_fu_1034_p1 = $signed(trunc_ln708_s_reg_1232);

assign tmp_2_fu_986_p4 = {{in_index_fu_980_p2[31:4]}};

assign tmp_32_fu_957_p4 = {{w16_V_q0[18:12]}};

assign tmp_s_fu_894_p17 = ap_phi_mux_in_index_0_i_i29_phi_fu_496_p6[3:0];

assign trunc_ln162_1_fu_932_p1 = w16_V_q0[11:0];

assign w16_V_address0 = zext_ln156_fu_872_p1;

assign w_index_fu_878_p2 = (6'd1 + ap_phi_mux_w_index30_phi_fu_258_p6);

assign zext_ln156_fu_872_p1 = ap_phi_mux_w_index30_phi_fu_258_p6;

endmodule //dense_wrapper_ap_ufixed_ap_fixed_16_6_5_3_0_config16_s
