// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pooling2d_cl_array_array_ap_fixed_1u_config2_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_ST_fsm_state1 = "1";
const sc_lv<3> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_ST_fsm_state6 = "100";
const bool pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_boolean_1 = true;
const sc_lv<32> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv32_1 = "1";
const bool pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_boolean_0 = false;
const sc_lv<1> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv1_0 = "0";
const sc_lv<1> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv1_1 = "1";
const sc_lv<14> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv14_0 = "00000000000000";
const sc_lv<14> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv14_3840 = "11100001000000";
const sc_lv<14> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv14_1 = "1";
const sc_lv<32> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv32_3 = "11";
const sc_lv<32> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv32_2 = "10";
const sc_lv<32> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv32_77 = "1110111";
const sc_lv<32> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv32_F = "1111";
const sc_lv<17> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv17_0 = "00000000000000000";
const sc_lv<32> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv32_4 = "100";
const sc_lv<32> pooling2d_cl_array_array_ap_fixed_1u_config2_s::ap_const_lv32_10 = "10000";

pooling2d_cl_array_array_ap_fixed_1u_config2_s::pooling2d_cl_array_array_ap_fixed_1u_config2_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141 = new shift_line_buffer_array_ap_fixed_1u_config2_s("call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141");
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_clk(ap_clk);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_rst(ap_rst);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_start(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_done(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_done);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_idle(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_idle);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_ready(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ready);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->in_elem_data_V_read(tmp_data_0_V_reg_689);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_1_V_read(kernel_data_V_1);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_2_V_read(kernel_data_V_2);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_3_V_read(kernel_data_V_3);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_5_V_read(kernel_data_V_5);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_6_V_read(kernel_data_V_6);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_7_V_read(kernel_data_V_7);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_9_V_read(kernel_data_V_9);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_10_V_read(kernel_data_V_10);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_11_V_read(kernel_data_V_11);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_13_V_read(kernel_data_V_13);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_14_V_read(kernel_data_V_14);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->kernel_window_15_V_read(kernel_data_V_15);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_0(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_0);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_1(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_1);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_2(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_2);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_3(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_3);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_4(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_4);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_5(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_5);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_6(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_6);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_7(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_7);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_8(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_8);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_9(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_9);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_10(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_10);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_11(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_11);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_12(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_12);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_13(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_13);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_14(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_14);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_return_15(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_15);
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141->ap_ce(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ce);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln211_fu_564_p2);
    sensitive << ( pY );

    SC_METHOD(thread_add_ln213_fu_576_p2);
    sensitive << ( ap_sig_allocacmp_sY_load );

    SC_METHOD(thread_add_ln216_fu_514_p2);
    sensitive << ( pX );

    SC_METHOD(thread_add_ln218_fu_526_p2);
    sensitive << ( sX );

    SC_METHOD(thread_add_ln233_fu_170_p2);
    sensitive << ( indvar_flatten_reg_119 );

    SC_METHOD(thread_add_ln703_10_fu_484_p2);
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_0 );
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_4 );

    SC_METHOD(thread_add_ln703_11_fu_490_p2);
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_5 );
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_6 );

    SC_METHOD(thread_add_ln703_12_fu_496_p2);
    sensitive << ( add_ln703_11_fu_490_p2 );
    sensitive << ( add_ln703_10_fu_484_p2 );

    SC_METHOD(thread_add_ln703_13_fu_502_p2);
    sensitive << ( add_ln703_12_fu_496_p2 );
    sensitive << ( add_ln703_9_fu_478_p2 );

    SC_METHOD(thread_add_ln703_1_fu_436_p2);
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_2 );
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_10 );

    SC_METHOD(thread_add_ln703_2_fu_442_p2);
    sensitive << ( add_ln703_1_fu_436_p2 );
    sensitive << ( add_ln703_fu_430_p2 );

    SC_METHOD(thread_add_ln703_3_fu_448_p2);
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_14 );
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_15 );

    SC_METHOD(thread_add_ln703_4_fu_454_p2);
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_3 );
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_13 );

    SC_METHOD(thread_add_ln703_5_fu_460_p2);
    sensitive << ( add_ln703_4_fu_454_p2 );
    sensitive << ( add_ln703_3_fu_448_p2 );

    SC_METHOD(thread_add_ln703_6_fu_596_p2);
    sensitive << ( add_ln703_2_reg_698 );
    sensitive << ( add_ln703_5_reg_703 );

    SC_METHOD(thread_add_ln703_7_fu_466_p2);
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_8 );
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_9 );

    SC_METHOD(thread_add_ln703_8_fu_472_p2);
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_1 );
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_7 );

    SC_METHOD(thread_add_ln703_9_fu_478_p2);
    sensitive << ( add_ln703_8_fu_472_p2 );
    sensitive << ( add_ln703_7_fu_466_p2 );

    SC_METHOD(thread_add_ln703_fu_430_p2);
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_11 );
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_12 );

    SC_METHOD(thread_and_ln185_1_fu_418_p2);
    sensitive << ( icmp_ln185_2_fu_396_p2 );
    sensitive << ( icmp_ln185_3_fu_406_p2 );

    SC_METHOD(thread_and_ln185_2_fu_424_p2);
    sensitive << ( and_ln185_1_fu_418_p2 );
    sensitive << ( and_ln185_fu_412_p2 );

    SC_METHOD(thread_and_ln185_fu_412_p2);
    sensitive << ( icmp_ln185_fu_376_p2 );
    sensitive << ( icmp_ln185_1_fu_386_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln233_reg_680 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( and_ln185_2_reg_694 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln233_reg_680 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( and_ln185_2_reg_694 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001_ignoreCallOp27);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln233_reg_680 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( and_ln185_2_reg_694 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln233_reg_680 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( and_ln185_2_reg_694 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0_ignore_call18);

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( icmp_ln233_reg_680 );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1_ignore_call18);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( icmp_ln233_reg_680 );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2_ignore_call18);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3);
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( and_ln185_2_reg_694 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter3_ignore_call18);
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( and_ln185_2_reg_694 );

    SC_METHOD(thread_ap_condition_143);
    sensitive << ( icmp_ln233_reg_680_pp0_iter1_reg );
    sensitive << ( icmp_ln203_fu_508_p2 );
    sensitive << ( icmp_ln207_fu_558_p2 );

    SC_METHOD(thread_ap_condition_220);
    sensitive << ( icmp_ln233_reg_680_pp0_iter1_reg );
    sensitive << ( icmp_ln203_fu_508_p2 );
    sensitive << ( icmp_ln207_fu_558_p2 );

    SC_METHOD(thread_ap_condition_814);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln233_reg_680_pp0_iter1_reg );
    sensitive << ( icmp_ln203_fu_508_p2 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln233_fu_164_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_phi_reg_pp0_iter0_storemerge_i_i_reg_130);

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_ap_sig_allocacmp_sY_load);
    sensitive << ( sY );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln203_reg_713 );
    sensitive << ( ap_phi_reg_pp0_iter3_storemerge_i_i_reg_130 );

    SC_METHOD(thread_call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001_ignoreCallOp27 );

    SC_METHOD(thread_call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start);
    sensitive << ( call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start_reg );

    SC_METHOD(thread_data_V_data_V_blk_n);
    sensitive << ( data_V_data_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln233_reg_680 );

    SC_METHOD(thread_data_V_data_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln233_reg_680 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_icmp_ln185_1_fu_386_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln233_reg_680_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_sig_allocacmp_sY_load );

    SC_METHOD(thread_icmp_ln185_2_fu_396_p2);
    sensitive << ( pY );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln233_reg_680_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_icmp_ln185_3_fu_406_p2);
    sensitive << ( pX );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln233_reg_680_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_icmp_ln185_fu_376_p2);
    sensitive << ( sX );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln233_reg_680_pp0_iter1_reg );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_icmp_ln203_fu_508_p2);
    sensitive << ( pX );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_icmp_ln207_fu_558_p2);
    sensitive << ( pY );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln203_fu_508_p2 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_icmp_ln233_fu_164_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( indvar_flatten_reg_119 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_res_V_data_V_blk_n);
    sensitive << ( res_V_data_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( and_ln185_2_reg_694 );

    SC_METHOD(thread_res_V_data_V_din);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( and_ln185_2_reg_694 );
    sensitive << ( ap_block_pp0_stage0_01001 );
    sensitive << ( res_pack_data_V_fu_661_p3 );

    SC_METHOD(thread_res_V_data_V_write);
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( and_ln185_2_reg_694 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_pack_data_V_fu_661_p3);
    sensitive << ( tmp_1_fu_609_p3 );
    sensitive << ( sub_ln1148_1_fu_651_p2 );
    sensitive << ( zext_ln1148_fu_657_p1 );

    SC_METHOD(thread_select_ln213_fu_582_p3);
    sensitive << ( icmp_ln185_1_fu_386_p2 );
    sensitive << ( add_ln213_fu_576_p2 );

    SC_METHOD(thread_select_ln218_fu_532_p3);
    sensitive << ( icmp_ln185_fu_376_p2 );
    sensitive << ( add_ln218_fu_526_p2 );

    SC_METHOD(thread_sext_ln1148_1_fu_647_p1);
    sensitive << ( trunc_ln1148_2_fu_637_p4 );

    SC_METHOD(thread_sext_ln1148_fu_605_p1);
    sensitive << ( sum_V_fu_600_p2 );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_sub_ln1148_1_fu_651_p2);
    sensitive << ( zext_ln1148_1_fu_633_p1 );

    SC_METHOD(thread_sub_ln1148_fu_617_p2);
    sensitive << ( sext_ln1148_fu_605_p1 );

    SC_METHOD(thread_sum_V_fu_600_p2);
    sensitive << ( add_ln703_13_reg_708 );
    sensitive << ( add_ln703_6_fu_596_p2 );

    SC_METHOD(thread_tmp_1_fu_609_p3);
    sensitive << ( sum_V_fu_600_p2 );

    SC_METHOD(thread_tmp_fu_623_p4);
    sensitive << ( sub_ln1148_fu_617_p2 );

    SC_METHOD(thread_trunc_ln1148_2_fu_637_p4);
    sensitive << ( sum_V_fu_600_p2 );

    SC_METHOD(thread_zext_ln1148_1_fu_633_p1);
    sensitive << ( tmp_fu_623_p4 );

    SC_METHOD(thread_zext_ln1148_fu_657_p1);
    sensitive << ( sext_ln1148_1_fu_647_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( icmp_ln233_fu_164_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    pX = "00000000000000000000000000000000";
    sX = "00000000000000000000000000000000";
    pY = "00000000000000000000000000000000";
    sY = "00000000000000000000000000000000";
    kernel_data_V_1 = "0000000000000000";
    kernel_data_V_2 = "0000000000000000";
    kernel_data_V_3 = "0000000000000000";
    kernel_data_V_5 = "0000000000000000";
    kernel_data_V_6 = "0000000000000000";
    kernel_data_V_7 = "0000000000000000";
    kernel_data_V_9 = "0000000000000000";
    kernel_data_V_10 = "0000000000000000";
    kernel_data_V_11 = "0000000000000000";
    kernel_data_V_13 = "0000000000000000";
    kernel_data_V_14 = "0000000000000000";
    kernel_data_V_15 = "0000000000000000";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pooling2d_cl_array_array_ap_fixed_1u_config2_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, data_V_data_V_dout, "(port)data_V_data_V_dout");
    sc_trace(mVcdFile, data_V_data_V_empty_n, "(port)data_V_data_V_empty_n");
    sc_trace(mVcdFile, data_V_data_V_read, "(port)data_V_data_V_read");
    sc_trace(mVcdFile, res_V_data_V_din, "(port)res_V_data_V_din");
    sc_trace(mVcdFile, res_V_data_V_full_n, "(port)res_V_data_V_full_n");
    sc_trace(mVcdFile, res_V_data_V_write, "(port)res_V_data_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, pX, "pX");
    sc_trace(mVcdFile, sX, "sX");
    sc_trace(mVcdFile, pY, "pY");
    sc_trace(mVcdFile, sY, "sY");
    sc_trace(mVcdFile, kernel_data_V_1, "kernel_data_V_1");
    sc_trace(mVcdFile, kernel_data_V_2, "kernel_data_V_2");
    sc_trace(mVcdFile, kernel_data_V_3, "kernel_data_V_3");
    sc_trace(mVcdFile, kernel_data_V_5, "kernel_data_V_5");
    sc_trace(mVcdFile, kernel_data_V_6, "kernel_data_V_6");
    sc_trace(mVcdFile, kernel_data_V_7, "kernel_data_V_7");
    sc_trace(mVcdFile, kernel_data_V_9, "kernel_data_V_9");
    sc_trace(mVcdFile, kernel_data_V_10, "kernel_data_V_10");
    sc_trace(mVcdFile, kernel_data_V_11, "kernel_data_V_11");
    sc_trace(mVcdFile, kernel_data_V_13, "kernel_data_V_13");
    sc_trace(mVcdFile, kernel_data_V_14, "kernel_data_V_14");
    sc_trace(mVcdFile, kernel_data_V_15, "kernel_data_V_15");
    sc_trace(mVcdFile, data_V_data_V_blk_n, "data_V_data_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln233_reg_680, "icmp_ln233_reg_680");
    sc_trace(mVcdFile, res_V_data_V_blk_n, "res_V_data_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, and_ln185_2_reg_694, "and_ln185_2_reg_694");
    sc_trace(mVcdFile, indvar_flatten_reg_119, "indvar_flatten_reg_119");
    sc_trace(mVcdFile, icmp_ln233_fu_164_p2, "icmp_ln233_fu_164_p2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3, "ap_block_state5_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln233_reg_680_pp0_iter1_reg, "icmp_ln233_reg_680_pp0_iter1_reg");
    sc_trace(mVcdFile, add_ln233_fu_170_p2, "add_ln233_fu_170_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_data_0_V_reg_689, "tmp_data_0_V_reg_689");
    sc_trace(mVcdFile, and_ln185_2_fu_424_p2, "and_ln185_2_fu_424_p2");
    sc_trace(mVcdFile, add_ln703_2_fu_442_p2, "add_ln703_2_fu_442_p2");
    sc_trace(mVcdFile, add_ln703_2_reg_698, "add_ln703_2_reg_698");
    sc_trace(mVcdFile, add_ln703_5_fu_460_p2, "add_ln703_5_fu_460_p2");
    sc_trace(mVcdFile, add_ln703_5_reg_703, "add_ln703_5_reg_703");
    sc_trace(mVcdFile, add_ln703_13_fu_502_p2, "add_ln703_13_fu_502_p2");
    sc_trace(mVcdFile, add_ln703_13_reg_708, "add_ln703_13_reg_708");
    sc_trace(mVcdFile, icmp_ln203_fu_508_p2, "icmp_ln203_fu_508_p2");
    sc_trace(mVcdFile, icmp_ln203_reg_713, "icmp_ln203_reg_713");
    sc_trace(mVcdFile, icmp_ln207_fu_558_p2, "icmp_ln207_fu_558_p2");
    sc_trace(mVcdFile, select_ln213_fu_582_p3, "select_ln213_fu_582_p3");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_done, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_done");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_idle, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_idle");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ready, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ready");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_0, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_0");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_1, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_1");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_2, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_2");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_3, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_3");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_4, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_4");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_5, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_5");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_6, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_6");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_7, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_7");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_8, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_8");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_9, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_9");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_10, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_10");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_11, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_11");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_12, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_12");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_13, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_13");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_14, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_14");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_15, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_15");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ce, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ce");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0_ignore_call18, "ap_block_state2_pp0_stage0_iter0_ignore_call18");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1_ignore_call18, "ap_block_state3_pp0_stage0_iter1_ignore_call18");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2_ignore_call18, "ap_block_state4_pp0_stage0_iter2_ignore_call18");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter3_ignore_call18, "ap_block_state5_pp0_stage0_iter3_ignore_call18");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001_ignoreCallOp27, "ap_block_pp0_stage0_11001_ignoreCallOp27");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter0_storemerge_i_i_reg_130, "ap_phi_reg_pp0_iter0_storemerge_i_i_reg_130");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter1_storemerge_i_i_reg_130, "ap_phi_reg_pp0_iter1_storemerge_i_i_reg_130");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter2_storemerge_i_i_reg_130, "ap_phi_reg_pp0_iter2_storemerge_i_i_reg_130");
    sc_trace(mVcdFile, ap_phi_reg_pp0_iter3_storemerge_i_i_reg_130, "ap_phi_reg_pp0_iter3_storemerge_i_i_reg_130");
    sc_trace(mVcdFile, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start_reg, "call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start_reg");
    sc_trace(mVcdFile, add_ln216_fu_514_p2, "add_ln216_fu_514_p2");
    sc_trace(mVcdFile, select_ln218_fu_532_p3, "select_ln218_fu_532_p3");
    sc_trace(mVcdFile, add_ln211_fu_564_p2, "add_ln211_fu_564_p2");
    sc_trace(mVcdFile, ap_sig_allocacmp_sY_load, "ap_sig_allocacmp_sY_load");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, icmp_ln185_fu_376_p2, "icmp_ln185_fu_376_p2");
    sc_trace(mVcdFile, icmp_ln185_1_fu_386_p2, "icmp_ln185_1_fu_386_p2");
    sc_trace(mVcdFile, icmp_ln185_2_fu_396_p2, "icmp_ln185_2_fu_396_p2");
    sc_trace(mVcdFile, icmp_ln185_3_fu_406_p2, "icmp_ln185_3_fu_406_p2");
    sc_trace(mVcdFile, and_ln185_1_fu_418_p2, "and_ln185_1_fu_418_p2");
    sc_trace(mVcdFile, and_ln185_fu_412_p2, "and_ln185_fu_412_p2");
    sc_trace(mVcdFile, add_ln703_1_fu_436_p2, "add_ln703_1_fu_436_p2");
    sc_trace(mVcdFile, add_ln703_fu_430_p2, "add_ln703_fu_430_p2");
    sc_trace(mVcdFile, add_ln703_4_fu_454_p2, "add_ln703_4_fu_454_p2");
    sc_trace(mVcdFile, add_ln703_3_fu_448_p2, "add_ln703_3_fu_448_p2");
    sc_trace(mVcdFile, add_ln703_8_fu_472_p2, "add_ln703_8_fu_472_p2");
    sc_trace(mVcdFile, add_ln703_7_fu_466_p2, "add_ln703_7_fu_466_p2");
    sc_trace(mVcdFile, add_ln703_11_fu_490_p2, "add_ln703_11_fu_490_p2");
    sc_trace(mVcdFile, add_ln703_10_fu_484_p2, "add_ln703_10_fu_484_p2");
    sc_trace(mVcdFile, add_ln703_12_fu_496_p2, "add_ln703_12_fu_496_p2");
    sc_trace(mVcdFile, add_ln703_9_fu_478_p2, "add_ln703_9_fu_478_p2");
    sc_trace(mVcdFile, add_ln218_fu_526_p2, "add_ln218_fu_526_p2");
    sc_trace(mVcdFile, add_ln213_fu_576_p2, "add_ln213_fu_576_p2");
    sc_trace(mVcdFile, add_ln703_6_fu_596_p2, "add_ln703_6_fu_596_p2");
    sc_trace(mVcdFile, sum_V_fu_600_p2, "sum_V_fu_600_p2");
    sc_trace(mVcdFile, sext_ln1148_fu_605_p1, "sext_ln1148_fu_605_p1");
    sc_trace(mVcdFile, sub_ln1148_fu_617_p2, "sub_ln1148_fu_617_p2");
    sc_trace(mVcdFile, tmp_fu_623_p4, "tmp_fu_623_p4");
    sc_trace(mVcdFile, trunc_ln1148_2_fu_637_p4, "trunc_ln1148_2_fu_637_p4");
    sc_trace(mVcdFile, zext_ln1148_1_fu_633_p1, "zext_ln1148_1_fu_633_p1");
    sc_trace(mVcdFile, sext_ln1148_1_fu_647_p1, "sext_ln1148_1_fu_647_p1");
    sc_trace(mVcdFile, tmp_1_fu_609_p3, "tmp_1_fu_609_p3");
    sc_trace(mVcdFile, sub_ln1148_1_fu_651_p2, "sub_ln1148_1_fu_651_p2");
    sc_trace(mVcdFile, zext_ln1148_fu_657_p1, "zext_ln1148_fu_657_p1");
    sc_trace(mVcdFile, res_pack_data_V_fu_661_p3, "res_pack_data_V_fu_661_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_143, "ap_condition_143");
    sc_trace(mVcdFile, ap_condition_220, "ap_condition_220");
    sc_trace(mVcdFile, ap_condition_814, "ap_condition_814");
#endif

    }
}

pooling2d_cl_array_array_ap_fixed_1u_config2_s::~pooling2d_cl_array_array_ap_fixed_1u_config2_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141;
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        if (esl_seteq<1,1,1>(ap_condition_220.read(), ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter3_storemerge_i_i_reg_130 = ap_const_lv32_0;
        } else if (esl_seteq<1,1,1>(ap_condition_143.read(), ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter3_storemerge_i_i_reg_130 = select_ln213_fu_582_p3.read();
        } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
            ap_phi_reg_pp0_iter3_storemerge_i_i_reg_130 = ap_phi_reg_pp0_iter2_storemerge_i_i_reg_130.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
             esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
            call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ready.read())) {
            call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln233_fu_164_p2.read()))) {
        indvar_flatten_reg_119 = add_ln233_fu_170_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        indvar_flatten_reg_119 = ap_const_lv14_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln203_fu_508_p2.read())) {
            pX = ap_const_lv32_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln203_fu_508_p2.read())) {
            pX = add_ln216_fu_514_p2.read();
        }
    }
    if (esl_seteq<1,1,1>(ap_condition_814.read(), ap_const_boolean_1)) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln207_fu_558_p2.read())) {
            pY = ap_const_lv32_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln207_fu_558_p2.read())) {
            pY = add_ln211_fu_564_p2.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln203_fu_508_p2.read())) {
            sX = ap_const_lv32_0;
        } else if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln203_fu_508_p2.read())) {
            sX = select_ln218_fu_532_p3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, and_ln185_2_fu_424_p2.read()))) {
        add_ln703_13_reg_708 = add_ln703_13_fu_502_p2.read();
        add_ln703_2_reg_698 = add_ln703_2_fu_442_p2.read();
        add_ln703_5_reg_703 = add_ln703_5_fu_460_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln233_reg_680_pp0_iter1_reg.read()))) {
        and_ln185_2_reg_694 = and_ln185_2_fu_424_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        ap_phi_reg_pp0_iter1_storemerge_i_i_reg_130 = ap_phi_reg_pp0_iter0_storemerge_i_i_reg_130.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        ap_phi_reg_pp0_iter2_storemerge_i_i_reg_130 = ap_phi_reg_pp0_iter1_storemerge_i_i_reg_130.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln203_reg_713 = icmp_ln203_fu_508_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln233_reg_680 = icmp_ln233_fu_164_p2.read();
        icmp_ln233_reg_680_pp0_iter1_reg = icmp_ln233_reg_680.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln233_reg_680_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()))) {
        kernel_data_V_1 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_4.read();
        kernel_data_V_10 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_11.read();
        kernel_data_V_11 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_12.read();
        kernel_data_V_13 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_13.read();
        kernel_data_V_14 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_14.read();
        kernel_data_V_15 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_15.read();
        kernel_data_V_2 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_5.read();
        kernel_data_V_3 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_6.read();
        kernel_data_V_5 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_7.read();
        kernel_data_V_6 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_8.read();
        kernel_data_V_7 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_9.read();
        kernel_data_V_9 = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_10.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln203_reg_713.read()))) {
        sY = ap_phi_reg_pp0_iter3_storemerge_i_i_reg_130.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_data_0_V_reg_689 = data_V_data_V_dout.read();
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln211_fu_564_p2() {
    add_ln211_fu_564_p2 = (!pY.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(pY.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln213_fu_576_p2() {
    add_ln213_fu_576_p2 = (!ap_sig_allocacmp_sY_load.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(ap_sig_allocacmp_sY_load.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln216_fu_514_p2() {
    add_ln216_fu_514_p2 = (!pX.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(pX.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln218_fu_526_p2() {
    add_ln218_fu_526_p2 = (!sX.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(sX.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln233_fu_170_p2() {
    add_ln233_fu_170_p2 = (!indvar_flatten_reg_119.read().is_01() || !ap_const_lv14_1.is_01())? sc_lv<14>(): (sc_biguint<14>(indvar_flatten_reg_119.read()) + sc_biguint<14>(ap_const_lv14_1));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_10_fu_484_p2() {
    add_ln703_10_fu_484_p2 = (!call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_4.read().is_01() || !call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_0.read().is_01())? sc_lv<16>(): (sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_4.read()) + sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_0.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_11_fu_490_p2() {
    add_ln703_11_fu_490_p2 = (!call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_6.read().is_01() || !call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_5.read().is_01())? sc_lv<16>(): (sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_6.read()) + sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_5.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_12_fu_496_p2() {
    add_ln703_12_fu_496_p2 = (!add_ln703_11_fu_490_p2.read().is_01() || !add_ln703_10_fu_484_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_11_fu_490_p2.read()) + sc_biguint<16>(add_ln703_10_fu_484_p2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_13_fu_502_p2() {
    add_ln703_13_fu_502_p2 = (!add_ln703_12_fu_496_p2.read().is_01() || !add_ln703_9_fu_478_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_12_fu_496_p2.read()) + sc_biguint<16>(add_ln703_9_fu_478_p2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_1_fu_436_p2() {
    add_ln703_1_fu_436_p2 = (!call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_10.read().is_01() || !call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_10.read()) + sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_2_fu_442_p2() {
    add_ln703_2_fu_442_p2 = (!add_ln703_1_fu_436_p2.read().is_01() || !add_ln703_fu_430_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1_fu_436_p2.read()) + sc_biguint<16>(add_ln703_fu_430_p2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_3_fu_448_p2() {
    add_ln703_3_fu_448_p2 = (!call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_14.read().is_01() || !call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_15.read().is_01())? sc_lv<16>(): (sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_14.read()) + sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_15.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_4_fu_454_p2() {
    add_ln703_4_fu_454_p2 = (!call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_13.read().is_01() || !call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_3.read().is_01())? sc_lv<16>(): (sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_13.read()) + sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_3.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_5_fu_460_p2() {
    add_ln703_5_fu_460_p2 = (!add_ln703_4_fu_454_p2.read().is_01() || !add_ln703_3_fu_448_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_4_fu_454_p2.read()) + sc_biguint<16>(add_ln703_3_fu_448_p2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_6_fu_596_p2() {
    add_ln703_6_fu_596_p2 = (!add_ln703_5_reg_703.read().is_01() || !add_ln703_2_reg_698.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_5_reg_703.read()) + sc_biguint<16>(add_ln703_2_reg_698.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_7_fu_466_p2() {
    add_ln703_7_fu_466_p2 = (!call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_8.read().is_01() || !call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_9.read().is_01())? sc_lv<16>(): (sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_8.read()) + sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_9.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_8_fu_472_p2() {
    add_ln703_8_fu_472_p2 = (!call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_7.read().is_01() || !call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_7.read()) + sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_1.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_9_fu_478_p2() {
    add_ln703_9_fu_478_p2 = (!add_ln703_8_fu_472_p2.read().is_01() || !add_ln703_7_fu_466_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_8_fu_472_p2.read()) + sc_biguint<16>(add_ln703_7_fu_466_p2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_add_ln703_fu_430_p2() {
    add_ln703_fu_430_p2 = (!call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_11.read().is_01() || !call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_12.read().is_01())? sc_lv<16>(): (sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_11.read()) + sc_biguint<16>(call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_return_12.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_and_ln185_1_fu_418_p2() {
    and_ln185_1_fu_418_p2 = (icmp_ln185_2_fu_396_p2.read() & icmp_ln185_3_fu_406_p2.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_and_ln185_2_fu_424_p2() {
    and_ln185_2_fu_424_p2 = (and_ln185_1_fu_418_p2.read() & and_ln185_fu_412_p2.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_and_ln185_fu_412_p2() {
    and_ln185_fu_412_p2 = (icmp_ln185_fu_376_p2.read() & icmp_ln185_1_fu_386_p2.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[2];
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(and_ln185_2_reg_694.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read())));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(and_ln185_2_reg_694.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read())));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_pp0_stage0_11001_ignoreCallOp27() {
    ap_block_pp0_stage0_11001_ignoreCallOp27 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(and_ln185_2_reg_694.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read())));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(and_ln185_2_reg_694.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read())));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_state2_pp0_stage0_iter0_ignore_call18() {
    ap_block_state2_pp0_stage0_iter0_ignore_call18 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_state3_pp0_stage0_iter1_ignore_call18() {
    ap_block_state3_pp0_stage0_iter1_ignore_call18 = (esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, data_V_data_V_empty_n.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_state4_pp0_stage0_iter2_ignore_call18() {
    ap_block_state4_pp0_stage0_iter2_ignore_call18 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_state5_pp0_stage0_iter3() {
    ap_block_state5_pp0_stage0_iter3 = (esl_seteq<1,1,1>(and_ln185_2_reg_694.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_block_state5_pp0_stage0_iter3_ignore_call18() {
    ap_block_state5_pp0_stage0_iter3_ignore_call18 = (esl_seteq<1,1,1>(and_ln185_2_reg_694.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, res_V_data_V_full_n.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_condition_143() {
    ap_condition_143 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln233_reg_680_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln203_fu_508_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln207_fu_558_p2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_condition_220() {
    ap_condition_220 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln233_reg_680_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln203_fu_508_p2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln207_fu_558_p2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_condition_814() {
    ap_condition_814 = (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln233_reg_680_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln203_fu_508_p2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln233_fu_164_p2.read())) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_done() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_phi_reg_pp0_iter0_storemerge_i_i_reg_130() {
    ap_phi_reg_pp0_iter0_storemerge_i_i_reg_130 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_sig_allocacmp_sY_load() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln203_reg_713.read()))) {
        ap_sig_allocacmp_sY_load = ap_phi_reg_pp0_iter3_storemerge_i_i_reg_130.read();
    } else {
        ap_sig_allocacmp_sY_load = sY.read();
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001_ignoreCallOp27.read(), ap_const_boolean_0))) {
        call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ce = ap_const_logic_1;
    } else {
        call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_ce = ap_const_logic_0;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start() {
    call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start = call_ret_shift_line_buffer_array_ap_fixed_1u_config2_s_fu_141_ap_start_reg.read();
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_data_V_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0))) {
        data_V_data_V_blk_n = data_V_data_V_empty_n.read();
    } else {
        data_V_data_V_blk_n = ap_const_logic_1;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_data_V_data_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln233_reg_680.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_V_data_V_read = ap_const_logic_1;
    } else {
        data_V_data_V_read = ap_const_logic_0;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_icmp_ln185_1_fu_386_p2() {
    icmp_ln185_1_fu_386_p2 = (!ap_sig_allocacmp_sY_load.read().is_01() || !ap_const_lv32_3.is_01())? sc_lv<1>(): sc_lv<1>(ap_sig_allocacmp_sY_load.read() == ap_const_lv32_3);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_icmp_ln185_2_fu_396_p2() {
    icmp_ln185_2_fu_396_p2 = (!pY.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<1>(): (sc_bigint<32>(pY.read()) > sc_bigint<32>(ap_const_lv32_2));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_icmp_ln185_3_fu_406_p2() {
    icmp_ln185_3_fu_406_p2 = (!pX.read().is_01() || !ap_const_lv32_2.is_01())? sc_lv<1>(): (sc_bigint<32>(pX.read()) > sc_bigint<32>(ap_const_lv32_2));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_icmp_ln185_fu_376_p2() {
    icmp_ln185_fu_376_p2 = (!sX.read().is_01() || !ap_const_lv32_3.is_01())? sc_lv<1>(): sc_lv<1>(sX.read() == ap_const_lv32_3);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_icmp_ln203_fu_508_p2() {
    icmp_ln203_fu_508_p2 = (!pX.read().is_01() || !ap_const_lv32_77.is_01())? sc_lv<1>(): sc_lv<1>(pX.read() == ap_const_lv32_77);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_icmp_ln207_fu_558_p2() {
    icmp_ln207_fu_558_p2 = (!pY.read().is_01() || !ap_const_lv32_77.is_01())? sc_lv<1>(): sc_lv<1>(pY.read() == ap_const_lv32_77);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_icmp_ln233_fu_164_p2() {
    icmp_ln233_fu_164_p2 = (!indvar_flatten_reg_119.read().is_01() || !ap_const_lv14_3840.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_119.read() == ap_const_lv14_3840);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_internal_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_res_V_data_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(and_ln185_2_reg_694.read(), ap_const_lv1_1))) {
        res_V_data_V_blk_n = res_V_data_V_full_n.read();
    } else {
        res_V_data_V_blk_n = ap_const_logic_1;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_res_V_data_V_din() {
    res_V_data_V_din = esl_sext<16,14>(res_pack_data_V_fu_661_p3.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_res_V_data_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(and_ln185_2_reg_694.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_V_data_V_write = ap_const_logic_1;
    } else {
        res_V_data_V_write = ap_const_logic_0;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_res_pack_data_V_fu_661_p3() {
    res_pack_data_V_fu_661_p3 = (!tmp_1_fu_609_p3.read()[0].is_01())? sc_lv<14>(): ((tmp_1_fu_609_p3.read()[0].to_bool())? sub_ln1148_1_fu_651_p2.read(): zext_ln1148_fu_657_p1.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_select_ln213_fu_582_p3() {
    select_ln213_fu_582_p3 = (!icmp_ln185_1_fu_386_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln185_1_fu_386_p2.read()[0].to_bool())? ap_const_lv32_0: add_ln213_fu_576_p2.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_select_ln218_fu_532_p3() {
    select_ln218_fu_532_p3 = (!icmp_ln185_fu_376_p2.read()[0].is_01())? sc_lv<32>(): ((icmp_ln185_fu_376_p2.read()[0].to_bool())? ap_const_lv32_0: add_ln218_fu_526_p2.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_sext_ln1148_1_fu_647_p1() {
    sext_ln1148_1_fu_647_p1 = esl_sext<13,12>(trunc_ln1148_2_fu_637_p4.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_sext_ln1148_fu_605_p1() {
    sext_ln1148_fu_605_p1 = esl_sext<17,16>(sum_V_fu_600_p2.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_start_out() {
    start_out = real_start.read();
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_sub_ln1148_1_fu_651_p2() {
    sub_ln1148_1_fu_651_p2 = (!ap_const_lv14_0.is_01() || !zext_ln1148_1_fu_633_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(ap_const_lv14_0) - sc_biguint<14>(zext_ln1148_1_fu_633_p1.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_sub_ln1148_fu_617_p2() {
    sub_ln1148_fu_617_p2 = (!ap_const_lv17_0.is_01() || !sext_ln1148_fu_605_p1.read().is_01())? sc_lv<17>(): (sc_biguint<17>(ap_const_lv17_0) - sc_bigint<17>(sext_ln1148_fu_605_p1.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_sum_V_fu_600_p2() {
    sum_V_fu_600_p2 = (!add_ln703_13_reg_708.read().is_01() || !add_ln703_6_fu_596_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_13_reg_708.read()) + sc_biguint<16>(add_ln703_6_fu_596_p2.read()));
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_tmp_1_fu_609_p3() {
    tmp_1_fu_609_p3 = sum_V_fu_600_p2.read().range(15, 15);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_tmp_fu_623_p4() {
    tmp_fu_623_p4 = sub_ln1148_fu_617_p2.read().range(16, 4);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_trunc_ln1148_2_fu_637_p4() {
    trunc_ln1148_2_fu_637_p4 = sum_V_fu_600_p2.read().range(15, 4);
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_zext_ln1148_1_fu_633_p1() {
    zext_ln1148_1_fu_633_p1 = esl_zext<14,13>(tmp_fu_623_p4.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_zext_ln1148_fu_657_p1() {
    zext_ln1148_fu_657_p1 = esl_zext<14,13>(sext_ln1148_1_fu_647_p1.read());
}

void pooling2d_cl_array_array_ap_fixed_1u_config2_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln233_fu_164_p2.read()) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln233_fu_164_p2.read()) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

