AcceleratorConfig:
  Board: alveo-u250
  Driver: python
  Interface: axi_stream
  Platform: xilinx_u250_xdma_201830_2
  Precision:
    Input: float
    Output: float
Backend: VivadoAccelerator
ClockPeriod: 5
HLSConfig:
  IOType: io_stream
  LayerName:
    average_pooling2d:
      Precision: ap_fixed<16,6>
      ReuseFactor: 64
      Trace: true
    batch_normalization:
      Precision:
        bias: ap_fixed<16,8>
        scale: ap_fixed<16,6>
      ReuseFactor: 64
      Trace: true
    batch_normalization_1:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 64
      Trace: true
    batch_normalization_2:
      Precision:
        bias: ap_fixed<16,6>
        scale: ap_fixed<16,6>
      ReuseFactor: 64
      Trace: true
    input_1:
      Precision:
        result: ap_fixed<16,6>
      ReuseFactor: 64
      Trace: true
    q_activation:
      Precision:
        result: ap_ufixed<12,3>
      ReuseFactor: 64
      Trace: true
    q_activation_1:
      Precision:
        result: ap_ufixed<12,3>
      ReuseFactor: 64
      Trace: true
    q_activation_1_quantized_relu:
      Precision:
        result: ap_ufixed<12,3>
      ReuseFactor: 64
      Trace: true
    q_activation_2:
      Precision:
        result: ap_ufixed<12,3>
      ReuseFactor: 64
      Trace: true
    q_activation_2_quantized_relu:
      Precision:
        result: ap_ufixed<12,3>
      ReuseFactor: 64
      Trace: true
    q_activation_quantized_relu:
      Precision:
        result: ap_ufixed<12,3>
      ReuseFactor: 64
      Trace: true
    q_dense:
      Precision:
        bias: ap_fixed<12,4>
        weight: ap_fixed<12,4>
      ReuseFactor: 64
      Trace: true
    q_dense_1:
      Precision:
        bias: ap_fixed<12,4>
        weight: ap_fixed<12,4>
      ReuseFactor: 64
      Trace: true
    q_dense_1_linear:
      Precision: ap_fixed<16,6>
      ReuseFactor: 64
      Trace: true
      table_size: 1024
      table_t: ap_fixed<18,8>
    q_dense_2:
      Precision:
        bias: ap_fixed<12,4>
        weight: ap_fixed<12,4>
      ReuseFactor: 64
      Trace: true
    q_dense_2_linear:
      Precision: ap_fixed<16,6>
      ReuseFactor: 64
      Trace: true
      table_size: 1024
      table_t: ap_fixed<18,8>
    q_dense_3:
      Precision:
        bias: ap_fixed<12,4>
        weight: ap_fixed<12,4>
      ReuseFactor: 64
      Trace: true
    q_dense_3_linear:
      Precision: ap_fixed<16,6>
      ReuseFactor: 64
      Trace: true
      table_size: 1024
      table_t: ap_fixed<18,8>
    q_dense_linear:
      Precision: ap_fixed<16,6>
      ReuseFactor: 64
      Trace: true
      table_size: 1024
      table_t: ap_fixed<18,8>
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 64
    Strategy: Resource
  OutputDir: ./models/mlp_average_pool_12b/my-hls-test
IOType: io_stream
KerasModel: !keras_model './models/mlp_average_pool_12b/my-hls-test/keras_model.h5'
OutputDir: ./models/mlp_average_pool_12b/my-hls-test
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 0dAA6bB6
