Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1
IOType: io_parallel
KerasH5: model_weights_.h5
KerasJson: model_arch_.json
OutputDir: my-hls-test
ProjectName: myproject
Stamp: ABBC84ac
XilinxPart: xcu200-fsgd2104-2-e
